port: 8001
whitelist:
  - 127.0.0.1
whitelistMode: false
basicAuthMode: true
basicAuthUser:
  username: user
  password: password
autorun: true
enableExtensions: true
listen: true
disableThumbnails: false
allowKeysExposure: false
securityOverride: false
skipContentCheck: false
requestOverrides: []
thumbnailsQuality: 95
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Xenova/all-mpnet-base-v2
  promptExpansionModel: Cohee/fooocus_expansion-onnx
enableCorsProxy: false
avatarThumbnailsPng: false
disableChatBackup: false
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
